version: '3.8'

services:
  tests:
    build:
      context: ./Back-End
      dockerfile: Dockerfile.test
    depends_on:
      - backend
      - sqlserver
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQL_SERVER_HOST=sqlserver
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=MySecureP@ss123
      - SQL_SERVER_DATABASE=master
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MySecureP@ss123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh  # Mount the entrypoint script
    command: chmod +x entrypoint.sh
    entrypoint: ["/bin/sh", "/usr/src/app/entrypoint.sh"]

networks:
  app-network:
    driver: bridge
