
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - SQL_SERVER_HOST=sqlserver
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=MySecureP@ss123
      - SQL_SERVER_DATABASE=master
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MySecureP@ss123
      - MSSQL_PID=Developer
    ports:
      - '1433:1433'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh  # Mount the entrypoint script
    entrypoint: ["/usr/src/app/entrypoint.sh"]  # Use the custom entrypoint script
    # healthcheck:
    #   test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "MySecureP@ss123", "-Q", "SELECT 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
