version: '3.8'

services:
  tests:
    build:
      context: ./Back-End
      dockerfile: Dockerfile.test
    depends_on:
      - backend
      - sqlserver
      - redis
    networks:
      - app-network
    entrypoint: >
      sh -c "
      ./ping-backend.sh &&
      npm test
      "

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQL_SERVER_HOST=sqlserver
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=MySecureP@ss123
      - SQL_SERVER_DATABASE=master
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    depends_on:
      - sqlserver
      - redis
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root  # Ensure the container runs as root for initialization
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MySecureP@ss123
      - MSSQL_PID=Developer
      - CORS_ORIGIN=http://167.71.165.174:3000
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint-sql.sh:/usr/src/app/entrypoint-sql.sh
    entrypoint: ["/bin/sh", "/usr/src/app/entrypoint-sql.sh"]
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
  redis-data:
