version: '3.8'

services:
  tests:
    build:
      context: ./Back-End
      dockerfile: Dockerfile.test
    depends_on:
      - backend
      - sqlserver
    networks:
      - app-network
    entrypoint: >
      sh -c "
      ./ping-backend.sh &&
      npm test
      "

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQL_SERVER_HOST=sqlserver
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=MySecureP@ss123
      - SQL_SERVER_DATABASE=master
    depends_on:
      - sqlserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/test-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MySecureP@ss123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint-sql.sh:/usr/src/app/entrypoint-sql.sh
    command: chmod +x entrypoint.sh
    entrypoint: ["/bin/sh", "/usr/src/app/entrypoint-sql.sh"]
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "MySecureP@ss123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
